# Site settings
title: Indian Girl in Germany
description: My immigration blog
baseurl: "/India-to-Germany/" # The subpath of your site, e.g., /blog/
url: "https://ichbinakanksha.github.io" # The base hostname & protocol for your site

# Build settings
theme: minima
title: Tech & Turmeric- An Indian Girl Abroad
author: Akanksha Bhardwaj
description: Follow my journey from humble beginnings in India to a thriving software engineer in Germany.
google:
  ad-client: "ca-pub-6333156648821428"
