theme: minima
title: Tech & Turmeric- An Indian Girl Abroad
author: Akanksha Bhardwaj
description: Follow my journey from humble beginnings in India to a thriving software engineer in Germany.
google:
  ad-client: "ca-pub-6333156648821428"
